version: 2

project_name: gozim

before:
  hooks:
    - go mod tidy
    - cd cmd && go mod tidy

builds:
  - id: zimcat
    dir: cmd
    main: ./zimcat
    binary: zimcat
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

  - id: ziminfo
    dir: cmd
    main: ./ziminfo
    binary: ziminfo
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

  - id: zimsearch
    dir: cmd
    main: ./zimsearch
    binary: zimsearch
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

  - id: zimserve
    dir: cmd
    main: ./zimserve
    binary: zimserve
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

  - id: zimverify
    dir: cmd
    main: ./zimverify
    binary: zimverify
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1
    - title: Other
      order: 999

release:
  prerelease: auto
